### ISSUE TITLE
Map TeamViewer-roles to spec. AD-Groups?

### ISSUE THREAD

**Issue by TheSwede86** [teamviewer/AD-Connector#17]
Hello,

Wondering if a future implementation will support mapping TeamViewer-roles such as:
Member, Admin, Company Admin
to specific AD-groups?

Today it syncs all users in the specified AD-groups as TeamViewer "members".

Best Regards

**Comment by ChristianJ-TV** [comment]
Hello TheSwede86,

we went into this direction with the release of our Rights and Roles (RBAC) functionality this year.

You can define roles with specific permissions in the TV Management Console and associate them with user groups (TV).
Afterwards, you synchronize users from AD user groups with the user groups (TV) you've created. The users thereby receive the permissions inherited from the role.

Best regards
