### ISSUE TITLE
[Bug] Failed to create TeamViewer user xxxxxxxx: @{error=invalid_request; error_description=Parameter "name" must have between 5 and 50 characters. 

### ISSUE THREAD

**Issue by kai-uwe-rommel** [teamviewer/AD-Connector#37]
**Summary**
The 'Parameter "name" must have between 5 and 50 characters. ' is a problem. We do have quite a number of users with last name of four or even only three letters. I assume this error is because of the last name. I see no way how I could influence this (except changing their name ...).
It could also be the login name or "user id" which in our AD is set to the last name of the user.
This is not clear from the error message.

**Expected Behavior**
Accept also user names with only three or four letters.

**Steps To Reproduce**
1. have users in your AD with shorter name
2. run sync job
3. see error in log

**Attachments**
Failed to create TeamViewer user xxxxx.yyyy@domain.tld: @{error=invalid_request; error_description=Parameter "name" must have between 5 and 50 characters.

**Comment by kai-uwe-rommel** [comment]
It could also be the login name or "user id" which in our AD is the last name of the user.

**Comment by ChristianJ-TV** [comment]
Hello @kai-uwe-rommel,

thanks for bringing this issue up.

The limit of the name field was changed in the web API, which is used by the ADC.
I've requested an API change (TeamViewer internally) and sugested to set it to two characters.

I will keep you informed.

Best,
Christian

**Comment by Zuescho** [comment]
Just wondering if this was fixed or is still open? @ChristianJ-TV

**Comment by ChristianJ-TV** [comment]
Hello,

sorry for the delayed answer - yes, API was adapted and allows now names with only two characters.

Best.
